---
version: "2.1"
services:
  babybuddy:
    image: lscr.io/linuxserver/babybuddy:latest
    container_name: babybuddy
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - CSRF_TRUSTED_ORIGINS=http://127.0.0.1:8000,https://babybuddy--9uux61q.mangoground-f9845c65.eastus.azurecontainerapps.io
      - DB_ENGINE=django.db.backends.postgresql
      - DB_HOST=server422139796.postgres.database.azure.com
      - DB_NAME=babybuddy
      - DB_USER=bouncybagels9
      - DB_PASSWORD=
    ports:
      - 8000:8000
    restart: unless-stopped
